spring.application.name=my-health
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/myHealthdb
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true